[licenses]
unused-allowed-license = "warn"
confidence-threshold = 0.95
allow = [
    "ISC",
    "Unicode-3.0",
    "MIT",
    "Apache-2.0",
    "EUPL-1.2",
    "BSD-3-Clause",
    "GPL-3.0",
    "CDLA-Permissive-2.0"
]

[advisories]
ignore = [
    "RUSTSEC-2023-0071" # https://rustsec.org/advisories/RUSTSEC-2023-0071
]
